name: credit_card_scanner
description: A Flutter package for both android and iOS which scan card credit. -
version: 0.0.8
repository: https://github.com/david2701/scanCard_Flutter.git
homepage:


environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.14.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.credit_card_scanner
        pluginClass: CreditCardScannerPlugin
      ios:
        pluginClass: CreditCardScannerPlugin
